//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccLedgerFee
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReferenceCode { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
    }
}
