//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppStudent
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public string Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CnicNo_FormBNo { get; set; }
        public Nullable<System.Guid> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.Guid> MartialStatusId { get; set; }
        public Nullable<System.Guid> ReligionId { get; set; }
        public Nullable<System.Guid> NationalityId { get; set; }
        public string ResedenitalAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ParentName { get; set; }
        public string ParentCnic { get; set; }
        public Nullable<System.Guid> ParentStudyLevelId { get; set; }
        public Nullable<System.Guid> OccupationId { get; set; }
        public Nullable<System.Guid> RelationshipId { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> DocumentStatus { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<int> DocType { get; set; }
    }
}
