//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanMethods
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfChallan { get; set; }
        public Nullable<int> TransactionMonth { get; set; }
    }
}
