//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralCompany
    {
        public System.Guid Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string AddressLine { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string CompanyWebsite { get; set; }
        public string UploadLogo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
