//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights
    {
        public int Id { get; set; }
        public string FormName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsDisplayAllowed { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Menu { get; set; }
    }
}
