//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SideMenu
    {
        public int Id { get; set; }
        public string ParentDisplay { get; set; }
        public string ModuleName { get; set; }
        public string Form { get; set; }
        public string URL { get; set; }
    }
}
